
select * from Retailssales.public_housing_inspections;
use Retailssales;
DROP TABLE IF EXISTS `one`;
create table one as
SELECT PUBLIC_HOUSING_AGENCY_NAME AS AGENCY_NAME,
INSPECTION_DATE AS INSPECT_DT, COST_OF_INSPECTION_IN_DOLLARS AS
INSPECT_COST,
LEAD(INSPECTION_DATE) OVER (PARTITION BY
PUBLIC_HOUSING_AGENCY_NAME ORDER BY
PUBLIC_HOUSING_AGENCY_NAME, INSPECTION_DATE DESC) AS
SECOND_INSPECT_DT,
LEAD(COST_OF_INSPECTION_IN_DOLLARS) OVER (PARTITION BY
PUBLIC_HOUSING_AGENCY_NAME ORDER BY
PUBLIC_HOUSING_AGENCY_NAME , INSPECTION_DATE DESC) AS
SECOND_INSPECT_COST,
COST_OF_INSPECTION_IN_DOLLARS -
(LEAD(COST_OF_INSPECTION_IN_DOLLARS) OVER (PARTITION BY
PUBLIC_HOUSING_AGENCY_NAME ORDER BY
PUBLIC_HOUSING_AGENCY_NAME , INSPECTION_DATE DESC)) AS
COST_CHANGE,
((COST_OF_INSPECTION_IN_DOLLARS -
(LEAD(COST_OF_INSPECTION_IN_DOLLARS) OVER (PARTITION BY
PUBLIC_HOUSING_AGENCY_NAME ORDER BY
PUBLIC_HOUSING_AGENCY_NAME , INSPECTION_DATE DESC)))/
(LEAD(COST_OF_INSPECTION_IN_DOLLARS) OVER (PARTITION BY
PUBLIC_HOUSING_AGENCY_NAME ORDER BY
PUBLIC_HOUSING_AGENCY_NAME , INSPECTION_DATE DESC))) * 100 AS
PERCENT_COST,

ROW_NUMBER() OVER (PARTITION BY PUBLIC_HOUSING_AGENCY_NAME
ORDER BY PUBLIC_HOUSING_AGENCY_NAME, INSPECTION_DATE DESC) AS
inspection_id from public_housing_inspections;
select * from one;
DROP TABLE IF EXISTS `two`;
create table two as
select AGENCY_NAME,
 INSPECT_DT,
INSPECT_COST,SECOND_INSPECT_DT,SECOND_INSPECT_COST,PERCENT_CO
ST
from one
 where inspection_id=1 and PERCENT_COST > 0;
select * from two;